<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DiplomaAnalysis.Common.Contracts\DiplomaAnalysis.Common.Contracts.csproj" />
    <ProjectReference Include="..\DiplomaAnalysis.Common.Extensions\DiplomaAnalysis.Common.Extensions.csproj" />
    <ProjectReference Include="..\DiplomaAnalysis.Common.Models\DiplomaAnalysis.Common.Models.csproj" />
  </ItemGroup>

</Project>
