name: Build and Deploy FrontEnd
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Patch API root
        run: |
          sed -i 's+http://localhost:7071+${{ vars.APPLICATION_PATH }}+g' DiplomaAnalysis.FrontEnd/app.js
        
      - name: Patch version
        run: |
          sed -i 's+v.0.0.0+v.1.0.0-beta.3+g' DiplomaAnalysis.FrontEnd/index.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.2
        with:
          branch: gh-pages
          folder: DiplomaAnalysis.FrontEnd